version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/usr/src/app
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DBL_TOKEN: ${DBL_TOKEN}
      PREFIX: ${PREFIX}
